apiVersion: v1
kind: Service
metadata:
  name: bookify-client-canary
  namespace: bookify
spec:
  selector:
    app: bookify-client-canary
  ports:
    - name: http-3000
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
