apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bookify-server-monitor
  namespace: bookify
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: bookify-server
  endpoints:
    - port: http-5000
      path: /metrics
      interval: 10s
      # Adding honorLabels to preserve labels from the target
      honorLabels: true
