apiVersion: v1
kind: Service
metadata:
  name: bookify-server
  namespace: default
spec:
  selector:
    app: bookify-server
  ports:
    - name: http-5000
      port: 5000
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer
