apiVersion: v1
kind: Service
metadata:
  name: bookify-payment
  namespace: bookify
spec:
  selector:
    app: bookify-payment
  ports:
    - name: http-8000
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: LoadBalancer
